
Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=GMT
    username: root
    password: 111
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
mybatis:
  type-aliases-package: com.nuedu.pojo
logging:
  level:
    com.nuedu.mapper: debug
